Fly/Fly.Web/Controllers/PostController.cs
using Fly.Domain.Models;
using Fly.Domain.Services;
using Fly.Domain.Services.Messaging;
using Fly.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Web.Controllers
{
    public class PostController : BaseController
    {
        //用户中心
        [AllowAnonymous]
        public ActionResult Index(int pageIndex = 1)
        {
            //获取第一页的三十条数据
            var request = new GetPagePostsRequest(pageIndex, PageSize);
            var response = new PostService().GetPagePostsByFilter(request);
            return View(response);
        }
        //未结贴
        [AllowAnonymous]
        public ActionResult Unsolved(int pageIndex = 1)
        {
            var request = new GetPagePostsRequest(pageIndex, PageSize)
            {
                PostStatus = PostStatus.Open
            };
            var response = new PostService().GetPagePostsByFilter(request);
            return View("Index", response);
        }
        //已采纳
        [AllowAnonymous]
        public ActionResult Solved(int pageIndex = 1)
        {
            var request = new GetPagePostsRequest(pageIndex, PageSize)
            {
                PostStatus = PostStatus.Close
            };
            var response = new PostService().GetPagePostsByFilter(request);
            return View("Index", response);
        }
        //精贴
        [AllowAnonymous]
        public ActionResult Wonderful(int pageIndex = 1)
        {
            var request = new GetPagePostsRequest(pageIndex, PageSize)
            {
                IsBoutique = true
            };
            var response = new PostService().GetPagePostsByFilter(request);
            return View("Index", response);
        }
        //详情
        [AllowAnonymous]
        public ActionResult Detail(int postId)
        {
            var service = new PostService();
            var post = service.GetPostById(postId);
            service.HitsPlusOne(post);
            ViewBag.CurrentUserId = CurrentUserId;
            ViewBag.IsAdmin = IsAdmin;

            var comments = new CommentService().GetPageCommentsByPostId(1, 20, postId);
            if (comments.IsSuccess && IsLogin)
            {
                var likeService = new LikeService();
                foreach (var item in comments.Pages.Items)
                {
                    item.IsLike = likeService.ZanIsExists(item.Id, CurrentUserId);
                }
            }
            ViewBag.Comments = comments;

            return View(post);
        }
        //发布帖子
        public ActionResult Add()
        {
            var postCategoryResponse = new PostCategoryService().GetPostCategories();
            ViewBag.PostCategories = postCategoryResponse.Items;

            return View();
        }
        //编辑帖子
        public ActionResult Edit(int postId)
        {
            var service = new PostService();
            if (!service.CheckIsEdit(CurrentUserId, postId))
            {
                return View();
            }
            var post = service.GetPostById(postId);
            ViewBag.PostCategories = new PostCategoryService().GetPostCategories().Items;
            return View(post);
        }
        //我的求解
        public ActionResult MinePost()
        {
            var page = Request["page"];
            var request = new GetPagePostsRequest(Convert.ToInt32(page), 10)
            {
                UserId = CurrentUserId
            };

            var response = new PostService().GetPagePostsByFilter(request);
            if (response.IsSuccess)
            {
                var rows = response.Pages.Items.Select(p =>
                {
                    return new
                    {
                        status = p.IsBoutique ? 1 : 0,
                        accept = p.PostStatus == PostStatus.Close ? 0 : -1,
                        id = p.Id,
                        title = p.Title,
                        time = p.CreateTime.ToString("yyyy-MM-dd HH:ss:mm"),
                        hits = p.Hits,
                        comment = p.CommentCount
                    };
                });


                return JsonResultForFly(0, response.Message, rows);
            }

            return JsonResultForFly(0, "暂无数据", new { });
        }
        //点赞
        [AllowAnonymous]
        public ActionResult JieDaZan(LikeModel model)
        {
            if (!IsLogin)
                return JsonResultForFly(1, "请先登录.");
            var response = new CommentService().AddOrRemoveLike(model.Id, model.Ok, CurrentUserId);
            return JsonResultForFly(response.IsSuccess ? 0 : 1, response.Message);
        }
        //删除帖子
        public ActionResult Delete()
        {
            if (!IsAdmin)
                return JsonResultForFly(1, "非法操作.");
            var id = Request["id"];

            var response = new PostService().DeletePost(Convert.ToInt32(id));

            return JsonResultForFly(response.IsSuccess ? 0 : 1, response.Message);
        }
        //设置
        public ActionResult Set(PostSetModel model)
        {
            if (!IsAdmin || model == null)
                return JsonResultForFly(1, "非法操作.");

            var response = new PostService().PostSet(model.Id, model.Rank, model.Field,CurrentUserId);

            return JsonResultForFly(response.IsSuccess ? 0 : 1, response.Message);
        }
        //帖子采纳
        [HttpPost]
        public ActionResult Accept(int id)
        {
            var response = new CommentService().Accept(CurrentUserId, id);

            return JsonResultForFly(response.IsSuccess ? 0 : 1, response.Message);
        }
        //回帖
        [HttpPost]
        [AllowAnonymous]
        [ValidateInput(false)]
        public ActionResult Reply(ReplyModel model)
        {
            if (!IsLogin)
                return JsonResultForFly(1, "你还没有登录呢，请登录后再来回复吧！");
            if (!EmailConfirmed)
                return JsonResultForFly(1, "请先验证邮箱哦.");
            var names = new List<string>();
            var arrNames = model.Content.Split('@');
            foreach (var item in arrNames)
            {
                var name = item.Length > 0 ? item.Substring(0, item.IndexOf(' ')) : item;
                if (name.Length > 0)
                    names.Add(name);
            }

            var entity = new Comment
            {
                UserId = CurrentUserId,
                PostId = model.Id,
                Like = 0,
                Content = model.Content,
                CreateTime = DateTime.Now,
                Ticks = DateTime.Now.Ticks
            };

            var response = new CommentService().AddComment(entity, CurrentUserId, names);

            return JsonResultForFly(response.IsSuccess ? 0 : 1, response.Message);
        }
        //编辑
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(PostModel model)
        {
            if (!EmailConfirmed)
                return JsonResultForFly(1, "请先验证邮箱哦.");
            return AddOrEdit(model);
        }
        //发贴
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add(PostModel model)
        {
            if (!EmailConfirmed)
                return JsonResultForFly(1, "请先验证邮箱哦.");
            return AddOrEdit(model);
        }
        //上传文件
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Upload(HttpPostedFileBase f)
        {
            if (!IsLogin)
                return JsonResultForFly(1, "请先登录.");
            try
            {
                var files = Request.Files;
                if (files.Count == 0)
                    return Json(new
                    {
                        status = 1,
                        msg = "请选择要修改的头像"
                    });
                if (!EmailConfirmed)
                    return JsonResultForFly(1, "请先验证邮箱哦.");

                var curFile = files[0];
                if ((curFile.ContentLength / 1024) > 150)
                {
                    return Json(new
                    {
                        status = 1,
                        msg = "请选择小于150KB的图片."
                    });
                }

                //获取保存路径
                var filesUrl = Server.MapPath("~/Uploads/PostImages/" + DateTime.Now.Year.ToString() + "/" + DateTime.Now.Month.ToString() + "/");
                if (Directory.Exists(filesUrl) == false)//路径不存在则创建
                    Directory.CreateDirectory(filesUrl);
                var fileName = Path.GetFileName(curFile.FileName);
                //文件后缀名
                var filePostfixName = fileName.Substring(fileName.LastIndexOf('.'));
                //新文件名
                var newFileName = DateTime.Now.ToString("yyyyMMddHHmmss") + filePostfixName;
                var path = Path.Combine(filesUrl, newFileName);
                //保存文件
                curFile.SaveAs(path);

                var newPath = Domain + "Uploads/PostImages/" + DateTime.Now.Year.ToString() + "/" + DateTime.Now.Month.ToString() + "/" + newFileName;

                return Json(new
                {
                    status = 0,
                    msg = "上传成功",
                    url = newPath
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = 1,
                    msg = "上传失败、错误信息：" + ex.Message
                });
            }
        }

        private ActionResult AddOrEdit(PostModel model)
        {
            if (model == null)
                return JsonResultForFly(1, "请勿传递非法参数，请刷新重试！");

            if (model.Title.Length < 10)
                return JsonResultForFly(1, "标题不能少于10个字符！");
            if (model.Content.Length < 20)
                return JsonResultForFly(1, "内容不能少于20个字符！");

            //验证验证码是否正确
            var sessionVerifyCode = Session["VerifyCode"];

Fly/Fly.Web/Controllers/ValidateCodeController.cs
using Fly.Domain.VerifyCode;
using System.Web.Mvc;

namespace Fly.Web.Controllers
{
    public class ValidateCodeController : Controller
    {
        // GET: ValidateCode
        public ActionResult GetValidateCode()
        {
            var vCode = new ValidateCode();
            string code = vCode.CreateValidateCode(5);
            Session["VerifyCode"] = code;
            byte[] bytes = vCode.CreateValidateGraphic(code);
            return File(bytes, @"image/jpeg");
        }
    }
}

Fly/Fly.Web/Views/Post/Add.cshtml
@{
    ViewBag.Title = "发表问题";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";


    var categories = ViewBag.PostCategories as IList<Fly.Domain.Models.PostCategory>;
}


<div class="main layui-clear">
    <h2 class="page-title">发表问题</h2>

    <!-- <div class="fly-none">并无权限</div> -->

    <div class="layui-form layui-form-pane">
        <form  method="post">
            @Html.AntiForgeryToken()
            <div class="layui-form-item">
                <label for="L_title" class="layui-form-label">标题</label>
                <div class="layui-input-block">
                    <input type="text" id="L_title" name="title" required lay-verify="required" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item layui-form-text">
                <div class="layui-input-block">
                    <textarea id="L_content" name="content" required lay-verify="required" placeholder="请输入内容" class="layui-textarea fly-editor" style="height: 260px;"></textarea>
                </div>
                <label for="L_content" class="layui-form-label" style="top: -2px;">描述</label>
            </div>
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">所在类别</label>
                    <div class="layui-input-block">
                        <select lay-verify="required" name="postCateogryId">
                            <option></option>
                            @if (categories != null && categories.Count > 0)
                            {
                                foreach (var item in categories)
                                {
                                    <option value="@item.Id">@item.CategoryName</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">悬赏飞吻</label>
                    <div class="layui-input-block">
                        <select name="reward">
                            <option value="5" selected>5</option>
                            <option value="20">20</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <label for="L_vercode" class="layui-form-label">人类验证</label>
                <div class="layui-input-inline">
                    <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">
                </div>
                <div class="layui-form-mid">
                    @*<span style="color: #c00;">1+1=?</span>*@
                    <img id="valiCode" src="@Url.Action("GetValidateCode", "ValidateCode", new { v = DateTime.Now.Ticks })" style="cursor:pointer;" alt="验证码" />
                </div>
            </div>
            <div class="layui-form-item">
                <button class="layui-btn" lay-filter="*" lay-submit>立即发布</button>
            </div>
        </form>
    </div>
</div>
@section scripts{
    <script>
        layui.use(['jquery','form'], function () {
            var $ = layui.jquery;

            $('#valiCode').off('click').on('click', function () {
                this.src = '@Url.Action("GetValidateCode", "ValidateCode")?v=' + new Date().getTime();
             });
        });
    </script>
}

Fly/Fly.Web/Views/Post/Detail.cshtml
@model Fly.Domain.Models.Post
@{
    ViewBag.Title =Model!=null ? Model.Title:"详情";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";

    var comments = ViewBag.Comments as Fly.Domain.Infrastructure.GetPagingResponse<Fly.Domain.Models.Comment>;
}

@if (Model != null)
{

    <div class="main layui-clear">
        <div class="wrap">
            <div class="content detail">
                <h1>@Model.Title</h1>
                <div class="fly-tip fly-detail-hint" data-id="@Model.Id">
                    @if (Model.IsTop)
                    {
                        <span class="fly-tip-stick">置顶帖</span>
                    }
                    @if (Model.IsBoutique)
                    {
                        <span class="fly-tip-jing">精帖</span>
                    }
                    @if (Model.PostStatus == Fly.Domain.Models.PostStatus.Open)
                    {
                        <span>未结贴</span>
                    }
                    else
                    {
                        <span class="fly-tip-jie">已采纳</span>
                    }
                    @if (ViewBag.IsAdmin)
                    {
                        <span class="jie-admin" type="del" style="margin-left: 20px;">删除</span>
                        if (!Model.IsTop)
                        {
                            <span class="jie-admin" type="set" field="stick" rank="1">置顶</span>
                        }
                        else
                        {
                            <span class="jie-admin" type="set" field="stick" rank="0" style="background-color:#ccc;">取消置顶</span>
                        }
                        if (!Model.IsBoutique)
                        {
                            <span class="jie-admin" type="set" field="status" rank="1">加精</span>
                        }
                        else
                        {
                            <span class="jie-admin" type="set" field="status" rank="0" style="background-color:#ccc;">取消加精</span>
                        }
                    }

                    <div class="fly-list-hint">
                        <i class="iconfont" title="回答">&#xe60c;</i> @Model.CommentCount
                        <i class="iconfont" title="人气">&#xe60b;</i> @Model.Hits
                    </div>
                </div>
                <div class="detail-about">
                    <a class="jie-user" href="@Url.Action("Home","Account",new { userId=Model.UserId })">
                        <img src="@Model.User.HeadPortrait" alt="">
                        <cite>
                            @Model.User.Nickname
                            <em>@Model.TimeAgo</em>
                        </cite>
                    </a>
                    <div class="detail-hits" data-id="@Model.Id">
                        <span style="color:#FF7200">悬赏：@Model.Reward 飞吻</span>
                        @if (ViewBag.CurrentUserId == Model.UserId && Model.PostStatus == Fly.Domain.Models.PostStatus.Open)
                        {
                            <span class="jie-admin" type="edit"><a href="@Url.Action("Edit", "Post", new { postId = Model.Id })">编辑此贴</a></span>
                        }
                    </div>
                </div>

                <div class="detail-body photos" style="margin-bottom: 20px;">
                    @Model.Content
                </div>

                <a name="comment"></a>
                <h2 class="page-title">热忱回答<span>（<em id="jiedaCount">@Model.CommentCount</em>）</span></h2>

                <ul class="jieda photos" id="jieda">
                    @if (comments.IsSuccess)
                    {
                        var isAdopt = comments.Pages.Items.Any(p => p.IsAdopt);
                        foreach (var item in comments.Pages.Items)
                        {
                            <li data-id="@item.Id" class="jieda-daan">
                                <a name="item_@item.Ticks"></a>
                                <div class="detail-about detail-about-reply">
                                    <a class="jie-user" href="@Url.Action("Home","Account",new { userId=item.UserId })">
                                        <img src="@item.User.HeadPortrait" alt="">
                                        <cite>
                                            <i>@item.User.Nickname</i>
                                            @if (item.User.Id == Model.UserId)
                                            {
                                                <em>(楼主)</em>
                                            }
                                            @if (item.User.IsAdmin)
                                            {
                                                <em style="color:#5FB878">(管理员)</em>
                                            }
                                            @if (!string.IsNullOrEmpty(item.User.Title))
                                            {
                                                <em style="color:#FF9E3F">（@item.User.Title）</em>
                                            }
                                            @if (item.User.IsDisabled)
                        {
                                                <em style="color:#999">（该号已被封）</em>
                                            }
                                        </cite>
                                    </a>
                                    <div class="detail-hits">
                                        <span>@item.TimeAgo</span>
                                    </div>
                                    @if (item.IsAdopt)
                        {
                                        <i class="iconfont icon-caina" title="最佳答案"></i>
                                    }
                                </div>
                                <div class="detail-body jieda-body">
                                    @item.Content
                                </div>
                                <div class="jieda-reply">
                                    @{ 
                                        var zanok = item.IsLike ? "zanok" : "";
                                    }
                                    <span class="jieda-zan   @zanok" type="zan"><i class="iconfont icon-zan"></i><em>@item.Like</em></span>
                                    <span type="reply"><i class="iconfont icon-svgmoban53"></i>回复</span>
                                    <div class="jieda-admin">
                                        <!--<span type="edit">编辑</span>
                                        <span type="del">删除</span>-->
                                        @if (Model.UserId == ViewBag.CurrentUserId && !isAdopt && item.UserId != Model.UserId)
                                        {
                                            <span class="jieda-accept" type="accept">采纳</span>
                                        }
                                    </div>
                                </div>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="fly-none">没有任何回答</li>
                    }

                </ul>

                <div class="layui-form layui-form-pane">
                    <form action="@Url.Action("Reply","Post")" method="post">
                        <div class="layui-form-item layui-form-text">
                            <div class="layui-input-block">
                                <textarea id="L_content" name="content" required lay-verify="required" placeholder="我要回答'" class="layui-textarea fly-editor" style="height: 150px;"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <input type="hidden" name="id" value="@Model.Id">
                            <button class="layui-btn" lay-filter="*" lay-submit>提交回答</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
        <div class="edge">

            <!--最近热帖 TOP8-->
            @{Html.RenderAction("LoadHotPostTopFifty");}
            <!--近期热议 TOP8-->
            @{Html.RenderAction("LoadHotCommentTopFifty");}

        </div>
    </div>
                }
                else
                {
                    <h2 class="page-title">404</h2>
                    <div class="fly-none">该问题并不存在，可能已被删除</div>
                }
@section scripts{
    <script>
    </script>

}

Fly/Fly.Web/Views/Post/Edit.cshtml
@model Fly.Domain.Models.Post
@{
    ViewBag.Title = "编辑问题";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";


    var categories = ViewBag.PostCategories as IList<Fly.Domain.Models.PostCategory>;
}


<div class="main layui-clear">
    <h2 class="page-title">发表问题</h2>
    @if (Model == null)
    {
        <div class="fly-none">不好意思哇，你并无权限操作此页面.<a href="@Url.Action("Index","Home")">返回首页</a></div>
    }
    else
    {

        <div class="layui-form layui-form-pane">
            <form method="post">
                @Html.AntiForgeryToken()
                <input type="hidden" name="id" value="@Model.Id" />
                <div class="layui-form-item">
                    <label for="L_title" class="layui-form-label">标题</label>
                    <div class="layui-input-block">
                        <input type="text" id="L_title" name="title" disabled required lay-verify="required" value="@Model.Title" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item layui-form-text">
                    <div class="layui-input-block">
                        <textarea id="L_content" name="content" required lay-verify="required" placeholder="请输入内容" class="layui-textarea fly-editor" style="height: 260px;">@Model.Content</textarea>
                    </div>
                    <label for="L_content" class="layui-form-label" style="top: -2px;">描述</label>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">所在类别</label>
                        <div class="layui-input-block">
                            <select lay-verify="required" name="postCateogryId">
                                <option></option>
                                @if (categories != null && categories.Count > 0)
                                {
                                    foreach (var item in categories)
                                    {
                                        var selected = item.Id == Model.PostCategoryId ? "selected" : "";
                                        <option value="@item.Id" @selected>@item.CategoryName</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">悬赏飞吻</label>
                        <div class="layui-input-block">
                            <select name="reward">
                                <option value="5" selected>5</option>
                                <option value="20">20</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="L_vercode" class="layui-form-label">人类验证</label>
                    <div class="layui-input-inline">
                        <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-form-mid">
                        <img id="valiCode" src="@Url.Action("GetValidateCode", "ValidateCode", new { v = DateTime.Now.Ticks })" style="cursor:pointer;" alt="验证码" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <button class="layui-btn" lay-filter="*" lay-submit>立即发布</button>
                </div>
            </form>
        </div>
    }
</div>
@section scripts{
    <script>
        layui.use(['jquery','form'], function () {
            var $ = layui.jquery;

            $('#valiCode').off('click').on('click', function () {
                this.src = '@Url.Action("GetValidateCode", "ValidateCode")?v=' + new Date().getTime();
             });
        });
    </script>
}